// Code generated by oapi-codegen (manual equivalent). DO NOT EDIT.
// Source: api/swagger.json

package internalhttp

import (
	"context"
	"encoding/json"
	"net/http"
	"strconv"
	"strings"
	"time"
)

// EventInput is the input body for creating or updating a calendar event.
type EventInput struct {
	Title        string    `json:"title"`
	DateTime     time.Time `json:"date_time"`
	EndDateTime  time.Time `json:"end_date_time"`
	Description  string    `json:"description,omitempty"`
	UserID       int64     `json:"user_id"`
	NotifyBefore int64     `json:"notify_before,omitempty"`
}

// EventResponse is the calendar event response model.
type EventResponse struct {
	ID           int64     `json:"id"`
	Title        string    `json:"title"`
	DateTime     time.Time `json:"date_time"`
	EndDateTime  time.Time `json:"end_date_time"`
	Description  string    `json:"description,omitempty"`
	UserID       int64     `json:"user_id"`
	NotifyBefore int64     `json:"notify_before,omitempty"`
}

// ErrorResponse is the error response model.
type ErrorResponse struct {
	Error string `json:"error"`
}

// StrictServerInterface defines the interface that handlers must implement.
type StrictServerInterface interface {
	CreateEvent(ctx context.Context, input EventInput) (EventResponse, error)
	UpdateEvent(ctx context.Context, id int64, input EventInput) (EventResponse, error)
	DeleteEvent(ctx context.Context, id int64) error
	ListEventsByDay(ctx context.Context, date time.Time) ([]EventResponse, error)
	ListEventsByWeek(ctx context.Context, date time.Time) ([]EventResponse, error)
	ListEventsByMonth(ctx context.Context, date time.Time) ([]EventResponse, error)
}

// RegisterHandlers registers all API routes on the given mux.
func RegisterHandlers(mux *http.ServeMux, si StrictServerInterface) {
	mux.HandleFunc("/events", func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodPost {
			handleCreateEvent(w, r, si)
			return
		}
		writeError(w, http.StatusMethodNotAllowed, "method not allowed")
	})

	mux.HandleFunc("/events/day", func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodGet {
			handleListEventsByDay(w, r, si)
			return
		}
		writeError(w, http.StatusMethodNotAllowed, "method not allowed")
	})

	mux.HandleFunc("/events/week", func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodGet {
			handleListEventsByWeek(w, r, si)
			return
		}
		writeError(w, http.StatusMethodNotAllowed, "method not allowed")
	})

	mux.HandleFunc("/events/month", func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodGet {
			handleListEventsByMonth(w, r, si)
			return
		}
		writeError(w, http.StatusMethodNotAllowed, "method not allowed")
	})

	mux.HandleFunc("/events/", func(w http.ResponseWriter, r *http.Request) {
		idStr := strings.TrimPrefix(r.URL.Path, "/events/")
		id, err := strconv.ParseInt(idStr, 10, 64)
		if err != nil {
			writeError(w, http.StatusBadRequest, "invalid event id")
			return
		}
		switch r.Method {
		case http.MethodPut:
			handleUpdateEvent(w, r, si, id)
		case http.MethodDelete:
			handleDeleteEvent(w, r, si, id)
		default:
			writeError(w, http.StatusMethodNotAllowed, "method not allowed")
		}
	})
}

func handleCreateEvent(w http.ResponseWriter, r *http.Request, si StrictServerInterface) {
	var input EventInput
	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		writeError(w, http.StatusBadRequest, "invalid request body: "+err.Error())
		return
	}
	result, err := si.CreateEvent(r.Context(), input)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeJSON(w, http.StatusCreated, result)
}

func handleUpdateEvent(w http.ResponseWriter, r *http.Request, si StrictServerInterface, id int64) {
	var input EventInput
	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		writeError(w, http.StatusBadRequest, "invalid request body: "+err.Error())
		return
	}
	result, err := si.UpdateEvent(r.Context(), id, input)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, result)
}

func handleDeleteEvent(w http.ResponseWriter, r *http.Request, si StrictServerInterface, id int64) {
	if err := si.DeleteEvent(r.Context(), id); err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

func handleListEventsByDay(w http.ResponseWriter, r *http.Request, si StrictServerInterface) {
	date, err := parseDate(r.URL.Query().Get("date"))
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid date: "+err.Error())
		return
	}
	events, err := si.ListEventsByDay(r.Context(), date)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, events)
}

func handleListEventsByWeek(w http.ResponseWriter, r *http.Request, si StrictServerInterface) {
	date, err := parseDate(r.URL.Query().Get("date"))
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid date: "+err.Error())
		return
	}
	events, err := si.ListEventsByWeek(r.Context(), date)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, events)
}

func handleListEventsByMonth(w http.ResponseWriter, r *http.Request, si StrictServerInterface) {
	date, err := parseDate(r.URL.Query().Get("date"))
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid date: "+err.Error())
		return
	}
	events, err := si.ListEventsByMonth(r.Context(), date)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, events)
}

func parseDate(s string) (time.Time, error) {
	return time.Parse("2006-01-02", s)
}

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

func writeError(w http.ResponseWriter, status int, msg string) {
	writeJSON(w, status, ErrorResponse{Error: msg})
}
