Level = "INFO"
LogLocation = "C:\\Users\\tovst\\GolandProjects\\golang-hw\\hw12_13_14_15_16_calendar\\logs\\log.log"
DbDriverName = "postgres"
Dsn = 'host=127.0.0.1 port=5433 user=postgres password=postgres dbname=postgres sslmode=disable'
Host = "127.0.0.1"
Port = 8080
Storage = "inner"
